"""
MCP Server for {{SITE_DESCRIPTION}}
Auto-generated by url-to-mcp skill

Target site: {{SITE_URL}}
"""

import json
import asyncio
from mcp.server.fastmcp import FastMCP
from playwright.async_api import async_playwright

mcp = FastMCP("{{SERVER_NAME}}")

SITE_URL = "{{SITE_URL}}"

# Browser configuration
BROWSER_ARGS = [
    "--disable-blink-features=AutomationControlled",
    "--no-sandbox",
]


async def _create_browser():
    """Create a browser instance with anti-detection settings."""
    pw = await async_playwright().start()
    browser = await pw.chromium.launch(
        headless=True,
        args=BROWSER_ARGS,
    )
    context = await browser.new_context(
        viewport={"width": 1280, "height": 720},
        user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    )
    page = await context.new_page()
    return pw, browser, page


async def _cleanup(pw, browser):
    """Close browser and stop playwright."""
    await browser.close()
    await pw.stop()


{{TOOLS}}


@mcp.tool()
async def take_screenshot(url: str = "", full_page: bool = False) -> str:
    """Take a screenshot of the target website or a specific URL.

    Args:
        url: URL to screenshot. Defaults to the main site URL if empty.
        full_page: Whether to capture the full page (scrolls down). Defaults to False.

    Returns:
        Path to the saved screenshot file.
    """
    target_url = url or SITE_URL
    pw, browser, page = None, None, None
    try:
        pw, browser, page = await _create_browser()
        await page.goto(target_url, wait_until="networkidle", timeout=30000)
        screenshot_path = f"/tmp/{SERVER_NAME}_screenshot.png"
        await page.screenshot(path=screenshot_path, full_page=full_page)
        return f"Screenshot saved to {screenshot_path}"
    except Exception as e:
        return f"Error taking screenshot: {str(e)}"
    finally:
        if browser:
            await _cleanup(pw, browser)


@mcp.tool()
async def get_page_content(url: str = "") -> str:
    """Get the text content of a page on the target website.

    Args:
        url: URL to fetch. Defaults to the main site URL if empty.

    Returns:
        The visible text content of the page.
    """
    target_url = url or SITE_URL
    pw, browser, page = None, None, None
    try:
        pw, browser, page = await _create_browser()
        await page.goto(target_url, wait_until="networkidle", timeout=30000)
        content = await page.inner_text("body")
        return content[:5000] if len(content) > 5000 else content
    except Exception as e:
        return f"Error fetching page content: {str(e)}"
    finally:
        if browser:
            await _cleanup(pw, browser)


@mcp.tool()
async def execute_custom_action(
    url: str = "",
    selector: str = "",
    action: str = "click",
    value: str = "",
    wait_after: int = 2000,
) -> str:
    """Execute a custom Playwright action on the target website.

    Args:
        url: URL to navigate to. Defaults to the main site URL if empty.
        selector: CSS selector for the target element.
        action: Action to perform - 'click', 'fill', 'select', 'hover', 'check'. Defaults to 'click'.
        value: Value to fill/select (required for 'fill' and 'select' actions).
        wait_after: Milliseconds to wait after the action. Defaults to 2000.

    Returns:
        Result description of the action performed.
    """
    target_url = url or SITE_URL
    pw, browser, page = None, None, None
    try:
        pw, browser, page = await _create_browser()
        await page.goto(target_url, wait_until="networkidle", timeout=30000)

        if not selector:
            return "Error: selector is required"

        element = await page.wait_for_selector(selector, timeout=10000)
        if not element:
            return f"Element not found: {selector}"

        if action == "click":
            await element.click()
        elif action == "fill":
            await element.fill(value)
        elif action == "select":
            await element.select_option(value)
        elif action == "hover":
            await element.hover()
        elif action == "check":
            await element.check()
        else:
            return f"Unknown action: {action}"

        await page.wait_for_timeout(wait_after)
        result = f"Action '{action}' performed on '{selector}'"
        if value:
            result += f" with value '{value}'"
        return result
    except Exception as e:
        return f"Error executing action: {str(e)}"
    finally:
        if browser:
            await _cleanup(pw, browser)


if __name__ == "__main__":
    mcp.run(transport="stdio")
