/**
 * MCP Server for {{SITE_DESCRIPTION}}
 * Auto-generated by url-to-mcp skill
 *
 * Target site: {{SITE_URL}}
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { chromium, type Browser, type Page } from "playwright";

const SERVER_NAME = "{{SERVER_NAME}}";
const SITE_URL = "{{SITE_URL}}";

const BROWSER_ARGS = [
  "--disable-blink-features=AutomationControlled",
  "--no-sandbox",
];

async function createBrowser(): Promise<{ browser: Browser; page: Page }> {
  const browser = await chromium.launch({
    headless: true,
    args: BROWSER_ARGS,
  });
  const context = await browser.newContext({
    viewport: { width: 1280, height: 720 },
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  });
  const page = await context.newPage();
  return { browser, page };
}

const server = new McpServer({
  name: SERVER_NAME,
  version: "1.0.0",
  description: "{{SITE_DESCRIPTION}}",
});

{{TOOLS}}

server.tool(
  "take_screenshot",
  "Take a screenshot of the target website or a specific URL.",
  {
    url: z.string().optional().describe("URL to screenshot. Defaults to main site URL."),
    full_page: z.boolean().optional().default(false).describe("Capture full page (scrolls down)."),
  },
  async ({ url, full_page }) => {
    const targetUrl = url || SITE_URL;
    let browser: Browser | null = null;
    try {
      const { browser: b, page } = await createBrowser();
      browser = b;
      await page.goto(targetUrl, { waitUntil: "networkidle", timeout: 30000 });
      const screenshotPath = `/tmp/${SERVER_NAME}_screenshot.png`;
      await page.screenshot({ path: screenshotPath, fullPage: full_page });
      await browser.close();
      return { content: [{ type: "text", text: `Screenshot saved to ${screenshotPath}` }] };
    } catch (error: any) {
      if (browser) await browser.close();
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
  }
);

server.tool(
  "get_page_content",
  "Get the text content of a page on the target website.",
  {
    url: z.string().optional().describe("URL to fetch. Defaults to main site URL."),
  },
  async ({ url }) => {
    const targetUrl = url || SITE_URL;
    let browser: Browser | null = null;
    try {
      const { browser: b, page } = await createBrowser();
      browser = b;
      await page.goto(targetUrl, { waitUntil: "networkidle", timeout: 30000 });
      const content = await page.innerText("body");
      await browser.close();
      const trimmed = content.length > 5000 ? content.substring(0, 5000) : content;
      return { content: [{ type: "text", text: trimmed }] };
    } catch (error: any) {
      if (browser) await browser.close();
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
  }
);

server.tool(
  "execute_custom_action",
  "Execute a custom Playwright action on the target website.",
  {
    url: z.string().optional().describe("URL to navigate to. Defaults to main site URL."),
    selector: z.string().describe("CSS selector for the target element."),
    action: z.enum(["click", "fill", "select", "hover", "check"]).default("click").describe("Action to perform."),
    value: z.string().optional().describe("Value for fill/select actions."),
    wait_after: z.number().optional().default(2000).describe("Wait time in ms after action."),
  },
  async ({ url, selector, action, value, wait_after }) => {
    const targetUrl = url || SITE_URL;
    let browser: Browser | null = null;
    try {
      const { browser: b, page } = await createBrowser();
      browser = b;
      await page.goto(targetUrl, { waitUntil: "networkidle", timeout: 30000 });

      const element = await page.waitForSelector(selector, { timeout: 10000 });
      if (!element) {
        await browser.close();
        return { content: [{ type: "text", text: `Element not found: ${selector}` }], isError: true };
      }

      switch (action) {
        case "click": await element.click(); break;
        case "fill": await element.fill(value || ""); break;
        case "select": await element.selectOption(value || ""); break;
        case "hover": await element.hover(); break;
        case "check": await element.check(); break;
      }

      await page.waitForTimeout(wait_after || 2000);
      await browser.close();
      let result = `Action '${action}' performed on '${selector}'`;
      if (value) result += ` with value '${value}'`;
      return { content: [{ type: "text", text: result }] };
    } catch (error: any) {
      if (browser) await browser.close();
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
  }
);

const transport = new StdioServerTransport();
await server.connect(transport);
